const PC_GAMES = [
  {
    id:'beamng-drive', name:'BeamNG.Drive', build:'0.32.3', platform:'PC', platformIcon:'🖥️',
    categories:['Simulation','Driving','Open World','Sandbox'],
    date:'2013-05-29', isHot:true, isFree:false, isNew:false,
    developer:'BeamNG GmbH', publisher:'BeamNG GmbH', engine:'BeamNG Engine', version:'0.32',
    languages:'Español, Inglés, Alemán, Francés, Ruso', online:'No / Multijugador con BeamMP',
    size:'25 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/284160/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/284160/page_bg_generated_v6b.jpg',
    screenshots:[
      'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/284160/ss_89f5f21840fcb3e0a4b7e5d1b5f3dd56b0b9c2a5.jpg',
      'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/284160/ss_e2a1f1f3c3b4d5e6a7b8c9d0e1f2a3b4c5d6e7f8.jpg',
      'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/284160/header.jpg',
    ],
    description:'BeamNG.drive es un simulador de conducción realista con física de destrucción de vehículos en tiempo real. Cada colisión, cada vuelta, cada salto se simula con un motor de física soft-body extremadamente preciso.',
    reqMin:{ OS:'Windows 10 64-bit', CPU:'Intel i3-6300 / AMD Ryzen 3 1300X', RAM:'8 GB', GPU:'NVIDIA GTX 970 / AMD RX 480 4GB', Storage:'20 GB', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel i7-8700K / AMD Ryzen 7 3800X', RAM:'16 GB', GPU:'NVIDIA RTX 2060 / AMD RX 5700', Storage:'25 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'12.4M', rating:'9.4', reviews:'148K', players:'42,000', peakPlayers:'78,000', avgHours:'320h' }
  },
  {
    id:'gta5', name:'Grand Theft Auto V', build:'1.0.3351', platform:'PC', platformIcon:'🖥️',
    categories:['Action','Open World','Crime','Adventure'],
    date:'2015-04-14', isHot:true, isFree:false, isNew:false,
    developer:'Rockstar North', publisher:'Rockstar Games', engine:'RAGE Engine', version:'1.0.3351',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Portugués, Ruso', online:'GTA Online',
    size:'100 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/271590/page_bg_generated_v6b.jpg',
    screenshots:[
      'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg',
    ],
    description:'Grand Theft Auto V es un juego de acción y aventura de mundo abierto ambientado en la ficticia ciudad de Los Santos. Con tres protagonistas jugables y un mundo masivo, GTA V ofrece una experiencia sin igual.',
    reqMin:{ OS:'Windows 10 64-bit', CPU:'Intel Core 2 Quad Q6600 @ 2.40GHz / AMD Phenom 9850 @ 2.5GHz', RAM:'4 GB', GPU:'NVIDIA 9800 GT 1GB / AMD HD 4870 1GB', Storage:'72 GB', DirectX:'DX 10' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i5-3470 @ 3.2GHz / AMD X8 FX-8350 @ 4GHz', RAM:'8 GB', GPU:'NVIDIA GTX 660 2GB / AMD HD 7870 2GB', Storage:'100 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'200M+', rating:'9.2', reviews:'1.2M', players:'150,000', peakPlayers:'364,000', avgHours:'200h' }
  },
  {
    id:'minecraft', name:'Minecraft Java Edition', build:'1.21.4', platform:'PC', platformIcon:'🖥️',
    categories:['Sandbox','Survival','Adventure','Indie'],
    date:'2011-11-18', isHot:true, isFree:false, isNew:false,
    developer:'Mojang Studios', publisher:'Microsoft / Mojang', engine:'Personalizado', version:'1.21.4',
    languages:'Español, Inglés, Francés, y 60+ idiomas', online:'Sí - Servidores Multijugador',
    size:'1 GB',
    thumb:'https://www.minecraft.net/content/dam/games/minecraft/key-art/Games_Subnav_Minecraft-300x465.jpg',
    headerImg:'https://www.minecraft.net/content/dam/games/minecraft/key-art/MC_Anniversary_KeyArt_2560x1440.jpg',
    screenshots:[],
    description:'Minecraft es un videojuego de mundo abierto donde puedes construir, explorar y sobrevivir en un universo generado proceduralmente formado por bloques. Uno de los juegos más vendidos de la historia.',
    reqMin:{ OS:'Windows 10 64-bit', CPU:'Intel Core i3-3210 / AMD A8-7600 APU', RAM:'4 GB', GPU:'Intel HD Graphics 4000 / AMD Radeon R5', Storage:'1 GB', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i5-4690 / AMD A10-7800 APU', RAM:'8 GB', GPU:'NVIDIA GTX 700 / AMD Radeon Rx 200', Storage:'4 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'300M+', rating:'9.5', reviews:'3.2M', players:'170M activos', peakPlayers:'Ilimitado', avgHours:'500h' }
  },
  {
    id:'cyberpunk2077', name:'Cyberpunk 2077', build:'2.12', platform:'PC', platformIcon:'🖥️',
    categories:['RPG','Action','Open World','Sci-Fi'],
    date:'2020-12-10', isHot:false, isFree:false, isNew:false,
    developer:'CD Projekt Red', publisher:'CD Projekt', engine:'REDengine 4', version:'2.12',
    languages:'Español, Inglés, Alemán, Francés, Italiano, Polaco, Portugués, Ruso, Chino, Japonés, Coreano', online:'No',
    size:'70 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1091500/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Cyberpunk 2077 es un RPG de acción de mundo abierto ambientado en Night City, una megalópolis obsesionada con el poder, la glamour y las modificaciones corporales. Encarnas a V, un mercenario en la búsqueda de un implante único.',
    reqMin:{ OS:'Windows 10 64-bit', CPU:'Intel Core i7-6700K / AMD Ryzen 5 1600', RAM:'8 GB', GPU:'NVIDIA GTX 1060 6GB / AMD Radeon RX 5500 XT 8GB', Storage:'70 GB SSD', DirectX:'DX 12' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i7-8700K / AMD Ryzen 5 3600', RAM:'12 GB', GPU:'NVIDIA RTX 2060 Super / AMD RX 5700 XT', Storage:'70 GB SSD', DirectX:'DX 12' },
    stats:{ downloads:'25M+', rating:'8.9', reviews:'520K', players:'18,000', peakPlayers:'1,054,388', avgHours:'90h' }
  },
  {
    id:'csgo', name:'Counter-Strike 2', build:'1.39.6.9', platform:'PC', platformIcon:'🖥️',
    categories:['FPS','Action','Shooter','Competitive'],
    date:'2023-09-27', isHot:true, isFree:true, isNew:false,
    developer:'Valve', publisher:'Valve', engine:'Source 2', version:'CS2',
    languages:'Español, Inglés, Francés, Alemán, y 20+ idiomas', online:'Sí - Multijugador',
    size:'25 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/730/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/730/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Counter-Strike 2 es el shooter táctico más jugado del mundo. Ahora en Source 2, CS2 lleva la experiencia de Counter-Strike a un nivel completamente nuevo con gráficos mejorados, física de humo reactiva y actualizaciones de jugabilidad.',
    reqMin:{ OS:'Windows 10 64-bit', CPU:'Intel Core i5-750 / AMD Phenom II X4 965', RAM:'8 GB', GPU:'NVIDIA GTX 1050 Ti / AMD RX 570', Storage:'25 GB', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i5-9600K / AMD Ryzen 5 3600', RAM:'16 GB', GPU:'NVIDIA GTX 1060 / AMD RX 5600 XT', Storage:'25 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'35M+', rating:'8.1', reviews:'2.1M', players:'800,000', peakPlayers:'1,818,773', avgHours:'1,200h' }
  },
  {
    id:'elden-ring', name:'Elden Ring', build:'1.14', platform:'PC', platformIcon:'🖥️',
    categories:['RPG','Action','Souls-like','Open World'],
    date:'2022-02-25', isHot:false, isFree:false, isNew:false,
    developer:'FromSoftware', publisher:'Bandai Namco', engine:'Dantelion Engine', version:'1.14',
    languages:'Español, Inglés, Japonés, Francés, Alemán, Italiano, Polaco, Coreano, Chino', online:'Sí - Co-op / PvP',
    size:'60 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1245620/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Elden Ring es un RPG de acción de mundo abierto desarrollado en colaboración con George R.R. Martin. Explora las Tierras Intermedias, un mundo vasto y misterioso lleno de desafíos legendarios.',
    reqMin:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i5-8400 / AMD Ryzen 3 3300X', RAM:'12 GB', GPU:'NVIDIA GTX 1060 3GB / AMD RX 580 4GB', Storage:'60 GB SSD', DirectX:'DX 12' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i7-8700K / AMD Ryzen 5 3600X', RAM:'16 GB', GPU:'NVIDIA GTX 1070 8GB / AMD RX Vega 56 8GB', Storage:'60 GB SSD', DirectX:'DX 12' },
    stats:{ downloads:'20M+', rating:'9.6', reviews:'355K', players:'22,000', peakPlayers:'953,426', avgHours:'110h' }
  },
  {
    id:'red-dead-2', name:'Red Dead Redemption 2', build:'1.0.1491', platform:'PC', platformIcon:'🖥️',
    categories:['Action','Adventure','Open World','Western'],
    date:'2019-11-05', isHot:false, isFree:false, isNew:false,
    developer:'Rockstar Games', publisher:'Rockstar Games', engine:'RAGE', version:'1.0.1491',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Polaco, Portugués, Ruso, Chino', online:'Red Dead Online',
    size:'150 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1174180/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Red Dead Redemption 2 es una epopeya del Lejano Oeste americano. Ambientada en 1899, sigue a Arthur Morgan, forajido de la pandilla Van der Linde, en una historia épica de supervivencia y redención.',
    reqMin:{ OS:'Windows 10 64-bit', CPU:'Intel Core i7-4770K / AMD Ryzen 5 1500X', RAM:'12 GB', GPU:'NVIDIA GTX 1060 6GB / AMD RX 480 4GB', Storage:'150 GB SSD', DirectX:'DX 12' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i7-4770K / AMD Ryzen 5 1500X', RAM:'12 GB', GPU:'NVIDIA GTX 1070 8GB / AMD RX 5500 XT 8GB', Storage:'150 GB SSD', DirectX:'DX 12' },
    stats:{ downloads:'50M+', rating:'9.7', reviews:'410K', players:'32,000', peakPlayers:'460,000', avgHours:'150h' }
  },
  {
    id:'the-witcher-3', name:'The Witcher 3: Wild Hunt', build:'4.04', platform:'PC', platformIcon:'🖥️',
    categories:['RPG','Open World','Fantasy','Adventure'],
    date:'2015-05-19', isHot:false, isFree:false, isNew:false,
    developer:'CD Projekt Red', publisher:'CD Projekt', engine:'REDengine 3', version:'4.04',
    languages:'Español, Inglés, Francés, Alemán, Polaco, Ruso, Chino, y 10+ idiomas', online:'No',
    size:'50 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/292030/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'The Witcher 3: Wild Hunt es un RPG de mundo abierto ganador de más de 800 premios. Juega como Geralt de Rivia, un cazador de monstruos, en una aventura épica en un mundo de fantasía oscura.',
    reqMin:{ OS:'Windows 7/8/10 64-bit', CPU:'Intel Core i5-2500K / AMD Phenom II X4 940', RAM:'6 GB', GPU:'NVIDIA GTX 660 / AMD R9 280', Storage:'50 GB', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i7-3770 / AMD FX-8350', RAM:'8 GB', GPU:'NVIDIA GTX 770 / AMD R9 290', Storage:'50 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'50M+', rating:'9.8', reviews:'750K', players:'48,000', peakPlayers:'300,000', avgHours:'180h' }
  },
  {
    id:'forza-horizon-5', name:'Forza Horizon 5', build:'3.633.223.0', platform:'PC', platformIcon:'🖥️',
    categories:['Racing','Simulation','Open World','Sports'],
    date:'2021-11-09', isHot:false, isFree:false, isNew:false,
    developer:'Playground Games', publisher:'Xbox Game Studios', engine:'ForzaTech', version:'3.633',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Japonés, Coreano, Portugués, Ruso, Chino', online:'Sí',
    size:'103 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1551360/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Forza Horizon 5 te lleva a México en una aventura de mundo abierto con más de 500 coches bajo licencia y una variedad de paisajes espectaculares. El juego de carreras de mundo abierto más ambicioso de Playground Games.',
    reqMin:{ OS:'Windows 10/11 64-bit', CPU:'Intel i5-4472 / AMD Ryzen 3 1200', RAM:'8 GB', GPU:'NVIDIA GTX 970 / AMD RX 470', Storage:'110 GB SSD', DirectX:'DX 12' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel i5-8400 / AMD Ryzen 5 1500X', RAM:'16 GB', GPU:'NVIDIA RTX 2060 / AMD RX 5700', Storage:'110 GB SSD', DirectX:'DX 12' },
    stats:{ downloads:'30M+', rating:'9.0', reviews:'185K', players:'14,000', peakPlayers:'240,000', avgHours:'120h' }
  },
  {
    id:'hogwarts-legacy', name:'Hogwarts Legacy', build:'1.0', platform:'PC', platformIcon:'🖥️',
    categories:['RPG','Action','Open World','Magic'],
    date:'2023-02-10', isHot:false, isFree:false, isNew:false,
    developer:'Avalanche Software', publisher:'Warner Bros. Games', engine:'Unreal Engine 4', version:'1.0',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Japonés, Coreano, Polaco, Portugués, Ruso, Chino', online:'No',
    size:'85 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/990080/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/990080/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Hogwarts Legacy es un RPG de acción de mundo abierto ambientado en el universo de Harry Potter en el siglo XIX. Crea tu propio mago, asiste a clases en Hogwarts y explora un vasto mundo mágico.',
    reqMin:{ OS:'Windows 10 64-bit', CPU:'Intel Core i5-6600 / AMD Ryzen 5 1400', RAM:'16 GB', GPU:'NVIDIA GTX 960 4GB / AMD RX 470 4GB', Storage:'85 GB SSD', DirectX:'DX 12' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i7-8700 / AMD Ryzen 5 3600', RAM:'16 GB', GPU:'NVIDIA RTX 2080 Ti / AMD RX 6800 XT', Storage:'85 GB SSD', DirectX:'DX 12' },
    stats:{ downloads:'22M+', rating:'8.7', reviews:'223K', players:'9,000', peakPlayers:'879,308', avgHours:'55h' }
  },
  {
    id:'animal-shelter-2', name:'Animal Shelter 2', build:'2256676', platform:'PC', platformIcon:'🖥️',
    categories:['Adventure','Casual','Indie','Simulation'],
    date:'2024-08-22', isNew:true, isFree:false, isHot:false,
    developer:'Gaming Factory S.A.', publisher:'Gaming Factory S.A.', engine:'Unreal Engine 5', version:'1.0',
    languages:'Español, Inglés, Francés, Alemán, Polaco', online:'No',
    size:'6 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2477810/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2477810/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Animal Shelter 2 es la secuela del exitoso simulador de refugio de animales. Gestiona tu propio refugio, cuida a los animales, encuéntrale un hogar a cada uno y expande tu instalación.',
    reqMin:{ OS:'Windows 10 64-bit', CPU:'Intel Core i5-8600K / AMD Ryzen 5 2600X', RAM:'8 GB', GPU:'NVIDIA GTX 1060 6GB / AMD RX 580', Storage:'6 GB SSD', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i7-9700K / AMD Ryzen 7 3700X', RAM:'16 GB', GPU:'NVIDIA RTX 2070 / AMD RX 5700 XT', Storage:'6 GB SSD', DirectX:'DX 12' },
    stats:{ downloads:'340K', rating:'8.2', reviews:'12K', players:'2,400', peakPlayers:'18,500', avgHours:'32h' }
  },
  {
    id:'baldurs-gate-3', name:"Baldur's Gate 3", build:'Patch 7', platform:'PC', platformIcon:'🖥️',
    categories:['RPG','Turn-Based','Fantasy','Co-op'],
    date:'2023-08-03', isHot:true, isFree:false, isNew:false,
    developer:'Larian Studios', publisher:'Larian Studios', engine:'Divinity 4.0', version:'Patch 7',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Polaco, Portugués, Ruso, Chino, Turco', online:'Sí - Co-op 4 jugadores',
    size:'122 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1086940/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:"Baldur's Gate 3 es un RPG de rol épico basado en D&D 5ª Edición. Reúne un grupo de aventureros y embárcate en una historia épica con libertad total de elección. Ganador del GOTY 2023.",
    reqMin:{ OS:'Windows 10 64-bit', CPU:'Intel i7-8700K / AMD Ryzen 5 3600', RAM:'8 GB', GPU:'NVIDIA GTX 1060 6GB / AMD RX 580', Storage:'150 GB SSD', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel i7-8700K / AMD Ryzen 5 3600', RAM:'16 GB', GPU:'NVIDIA RTX 2060 Super / AMD RX 5700 XT', Storage:'150 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'15M+', rating:'9.8', reviews:'542K', players:'60,000', peakPlayers:'875,343', avgHours:'200h' }
  },
  {
    id:'starfield', name:'Starfield', build:'1.14.74', platform:'PC', platformIcon:'🖥️',
    categories:['RPG','Sci-Fi','Open World','Space'],
    date:'2023-09-06', isNew:false, isFree:false, isHot:false,
    developer:'Bethesda Game Studios', publisher:'Bethesda Softworks', engine:'Creation Engine 2', version:'1.14',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Japonés, Polaco, Portugués, Ruso, Chino', online:'No',
    size:'125 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1716740/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1716740/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Starfield es la primera nueva IP de Bethesda en 25 años. Explora más de 1,000 planetas en el año 2330, únete a la Constelación y busca los artefactos que revelarán los misterios del universo.',
    reqMin:{ OS:'Windows 10/11 64-bit', CPU:'AMD Ryzen 5 2600X / Intel Core i7-6800K', RAM:'16 GB', GPU:'AMD RX 5700 / NVIDIA GeForce GTX 1070 Ti', Storage:'125 GB SSD', DirectX:'DX 12' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'AMD Ryzen 5 3600X / Intel Core i5-10600K', RAM:'16 GB', GPU:'AMD RX 6800 XT / NVIDIA GeForce RTX 2080', Storage:'125 GB SSD', DirectX:'DX 12' },
    stats:{ downloads:'12M+', rating:'7.4', reviews:'134K', players:'11,000', peakPlayers:'330,723', avgHours:'60h' }
  },
  {
    id:'dota2', name:'Dota 2', build:'7.36d', platform:'PC', platformIcon:'🖥️',
    categories:['MOBA','Strategy','Action','Multiplayer'],
    date:'2013-07-09', isHot:true, isFree:true, isNew:false,
    developer:'Valve', publisher:'Valve', engine:'Source 2', version:'7.36d',
    languages:'Español, Inglés, Chino, Ruso, Alemán, Francés, y 20+ idiomas', online:'Sí - Obligatorio',
    size:'50 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/570/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/570/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Dota 2 es un MOBA de equipo en el que dos equipos de 5 jugadores compiten por destruir la base del contrario. Con más de 120 héroes y un metagame en constante evolución, Dota 2 es el esport más competitivo del mundo.',
    reqMin:{ OS:'Windows 7/Vista/XP', CPU:'Dual core processor 2.8 GHz', RAM:'4 GB', GPU:'NVIDIA GeForce 8600 / ATI Radeon HD 2600', Storage:'15 GB', DirectX:'DX 9' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Intel Core i5 / AMD Ryzen 5', RAM:'8 GB', GPU:'NVIDIA GTX 1060 / AMD R9 290X', Storage:'50 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'80M+', rating:'8.8', reviews:'1.2M', players:'400,000', peakPlayers:'1,295,114', avgHours:'2,000h' }
  },
  {
    id:'valheim', name:'Valheim', build:'0.218.19', platform:'PC', platformIcon:'🖥️',
    categories:['Survival','Co-op','Norse','Indie'],
    date:'2021-02-02', isHot:false, isFree:false, isNew:false,
    developer:'Iron Gate Studio', publisher:'Coffee Stain Publishing', engine:'Unity', version:'0.218',
    languages:'Español, Inglés, Alemán, Francés, Ruso, Chino, Japonés, y 10+ idiomas', online:'Sí - Co-op hasta 10',
    size:'1 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/892970/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/892970/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Valheim es un juego de supervivencia y exploración inspirado en la mitología nórdica. Construye, explora y sobrevive en un vasto mundo procedimental de bosques, montañas y mazmorras mientras luchas contra criaturas épicas.',
    reqMin:{ OS:'Windows 7/10 64-bit', CPU:'FX-8370 / i5-3470', RAM:'8 GB', GPU:'GeForce GTX 970 / Radeon RX 480', Storage:'1 GB', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'i7-4770 / FX-8350', RAM:'16 GB', GPU:'GeForce GTX 1080 / Radeon RX 5700', Storage:'1 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'12M+', rating:'9.1', reviews:'282K', players:'18,000', peakPlayers:'502,387', avgHours:'150h' }
  },
  {
    id:'palworld', name:'Palworld', build:'0.3.6', platform:'PC', platformIcon:'🖥️',
    categories:['Survival','Action','Open World','Indie'],
    date:'2024-01-19', isHot:true, isFree:false, isNew:true,
    developer:'Pocketpair', publisher:'Pocketpair', engine:'Unreal Engine 5', version:'0.3.6',
    languages:'Español, Inglés, Japonés, Francés, Alemán, Italiano, Coreano, Portugués, Chino', online:'Sí - Multijugador',
    size:'40 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1623730/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1623730/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Palworld es un juego multijugador de mundo abierto donde capturas y entrenas criaturas llamadas Pals para luchar, construir y trabajar en tu granja. Combina elementos de supervivencia, crafting y acción.',
    reqMin:{ OS:'Windows 10/11 64-bit', CPU:'i5-3570K 3.4GHz / AMD Ryzen 5 3600', RAM:'16 GB', GPU:'NVIDIA GTX 1070 8GB', Storage:'40 GB SSD', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'i9-9900K / AMD Ryzen 9 3900X', RAM:'32 GB', GPU:'NVIDIA RTX 2070', Storage:'40 GB SSD', DirectX:'DX 12' },
    stats:{ downloads:'25M+', rating:'8.3', reviews:'232K', players:'62,000', peakPlayers:'2,101,048', avgHours:'80h' }
  },
  {
    id:'stardew-valley', name:'Stardew Valley', build:'1.6.8', platform:'PC', platformIcon:'🖥️',
    categories:['Farming','Simulation','Indie','RPG'],
    date:'2016-02-26', isHot:false, isFree:false, isNew:false,
    developer:'ConcernedApe', publisher:'ConcernedApe', engine:'Personalizado', version:'1.6.8',
    languages:'Español, Inglés, Alemán, Francés, Italiano, Japonés, Coreano, Portugués, Ruso, Chino, Turco', online:'Sí - Co-op 4',
    size:'500 MB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/413150/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Stardew Valley es un RPG de simulación de granja. Hereda una destartalada finca de tu abuelo y transforma la tierra en una granja floreciente. Cultiva, cría animales, explora minas y forma amistades en el pueblo.',
    reqMin:{ OS:'Windows Vista/7/8/10/11', CPU:'2 GHz', RAM:'2 GB', GPU:'256mb video memory, supports DirectX 9+', Storage:'500 MB', DirectX:'DX 9' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'i5 o superior', RAM:'4 GB', GPU:'512mb video memory', Storage:'500 MB SSD', DirectX:'DX 11' },
    stats:{ downloads:'30M+', rating:'9.7', reviews:'740K', players:'35,000', peakPlayers:'200,000', avgHours:'230h' }
  },
  {
    id:'hades', name:'Hades', build:'1.38496', platform:'PC', platformIcon:'🖥️',
    categories:['Roguelite','Action','Indie','Dungeon'],
    date:'2020-09-17', isHot:false, isFree:false, isNew:false,
    developer:'Supergiant Games', publisher:'Supergiant Games', engine:'Personalizado', version:'1.38496',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Japonés, Coreano, Portugués, Ruso, Chino', online:'No',
    size:'2 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1145360/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Hades es un roguelite de acción de Supergiant Games donde juegas como Zagreo, hijo del dios del inframundo, intentando escapar del reino de los muertos. Con combate frenético y narrativa excepcional.',
    reqMin:{ OS:'Windows 7 SP1 64-bit', CPU:'Dual Core 2.4 GHz', RAM:'4 GB', GPU:'1 GB VRAM / OpenGL 4+', Storage:'20 GB', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10 64-bit', CPU:'Quad Core 3.0 GHz', RAM:'8 GB', GPU:'2 GB VRAM', Storage:'20 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'8M+', rating:'9.6', reviews:'139K', players:'8,000', peakPlayers:'100,000', avgHours:'120h' }
  },
  {
    id:'among-us', name:'Among Us', build:'2024.9.4', platform:'PC', platformIcon:'🖥️',
    categories:['Social Deduction','Party','Indie','Multiplayer'],
    date:'2018-06-15', isHot:false, isFree:false, isNew:false,
    developer:'Innersloth', publisher:'Innersloth', engine:'Unity', version:'2024.9',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Japonés, Coreano, Portugués, Ruso, Chino', online:'Sí',
    size:'250 MB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/945360/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/945360/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Among Us es un juego multijugador de deducción social. Trabaja con tu tripulación para completar tareas mientras tratas de descubrir quién es el impostor que sabotea la nave y elimina a sus compañeros.',
    reqMin:{ OS:'Windows 7 SP1+', CPU:'SSE2 instruction set support', RAM:'1 GB', GPU:'DX10 capable graphics', Storage:'250 MB', DirectX:'DX 10' },
    reqRec:{ OS:'Windows 10/11', CPU:'Intel Core i3+', RAM:'2 GB', GPU:'DX11 capable', Storage:'250 MB SSD', DirectX:'DX 11' },
    stats:{ downloads:'500M+', rating:'7.8', reviews:'280K', players:'45,000', peakPlayers:'1,500,000', avgHours:'40h' }
  },
  {
    id:'hollow-knight', name:'Hollow Knight', build:'1.5.78.11833', platform:'PC', platformIcon:'🖥️',
    categories:['Metroidvania','Action','Indie','Adventure'],
    date:'2017-02-24', isHot:false, isFree:false, isNew:false,
    developer:'Team Cherry', publisher:'Team Cherry', engine:'Unity', version:'1.5.78',
    languages:'Español, Inglés, Alemán, Francés, Italiano, Japonés, Coreano, Portugués, Ruso, Chino', online:'No',
    size:'9 GB',
    thumb:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg',
    headerImg:'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/367520/page_bg_generated_v6b.jpg',
    screenshots:[],
    description:'Hollow Knight es un juego de acción y aventura metroidvania en un vasto reino subterráneo lleno de insectos. Explora cavernas retorcidas, lucha contra criaturas terribles y forja tu propio camino.',
    reqMin:{ OS:'Windows 7 SP1+', CPU:'Intel Core i3-3225 3.3 GHz', RAM:'4 GB', GPU:'GeForce 400 series+ / AMD Radeon 5000 series+', Storage:'9 GB', DirectX:'DX 11' },
    reqRec:{ OS:'Windows 10', CPU:'Intel Core i7 4500U', RAM:'8 GB', GPU:'GeForce GTX 760', Storage:'9 GB SSD', DirectX:'DX 11' },
    stats:{ downloads:'15M+', rating:'9.4', reviews:'185K', players:'6,000', peakPlayers:'50,000', avgHours:'85h' }
  },
];