const MOBILE_APPS = [
  {
    id:'spotify-mobile', name:'Spotify — Música y Podcasts', build:'8.9.98.488', platform:'Android/iOS', platformIcon:'📲',
    categories:['Música','Streaming','Social','Entretenimiento'],
    date:'2008-10-07', isHot:true, isFree:true, isNew:false,
    developer:'Spotify AB', publisher:'Spotify', engine:'Personalizado', version:'8.9.98',
    languages:'Español, Inglés, Francés, Alemán, y 40+ idiomas', online:'Sí - Streaming',
    size:'130 MB',
    thumb:'oip6.png',
    headerImg:'', screenshots:[],
    description:'Spotify es el servicio de streaming de música más popular del mundo con más de 100 millones de canciones, podcasts y audiolibros. Descubre nueva música, crea playlists y escucha sin conexión con Premium.',
    reqMin:{ OS:'Android 8.0+ / iOS 16+', RAM:'1 GB', Storage:'130 MB', Red:'Wi-Fi o datos' },
    reqRec:{ OS:'Android 10+ / iOS 17+', RAM:'2 GB', Storage:'500 MB', Red:'Wi-Fi para descarga' },
    stats:{ downloads:'5B+', rating:'8.8', reviews:'80M', players:'602M activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
  {
    id:'whatsapp', name:'WhatsApp Messenger', build:'2.24.23.76', platform:'Android/iOS', platformIcon:'📲',
    categories:['Mensajería','Comunicación','Social','Utilidades'],
    date:'2009-01-01', isHot:false, isFree:true, isNew:false,
    developer:'Meta Platforms', publisher:'Meta', engine:'Personalizado', version:'2.24.23',
    languages:'Español, Inglés, y 60+ idiomas', online:'Sí - Obligatorio',
    size:'50 MB',
    thumb:'https://play-lh.googleusercontent.com/bYtqbOcTYOlgc6gqZ2rwb8lptHuwlNE75zYJu6Bn076-hTmvd96HH-6v7S0YUAAJXoJN',
    headerImg:'', screenshots:[],
    description:'WhatsApp es la aplicación de mensajería más popular del mundo. Envía mensajes, fotos, videos, documentos y realiza llamadas y videollamadas gratuitas a cualquier parte del mundo.',
    reqMin:{ OS:'Android 5.0+ / iOS 15.1+', RAM:'1 GB', Storage:'50 MB', Red:'Wi-Fi o datos' },
    reqRec:{ OS:'Android 9+ / iOS 16+', RAM:'2 GB', Storage:'200 MB', Red:'Wi-Fi' },
    stats:{ downloads:'5B+', rating:'8.0', reviews:'200M', players:'2B activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
  {
    id:'tiktok-mobile', name:'TikTok', build:'36.1.4', platform:'Android/iOS', platformIcon:'📲',
    categories:['Vídeo','Social','Entretenimiento','Creación'],
    date:'2016-09-01', isHot:true, isFree:true, isNew:false,
    developer:'ByteDance', publisher:'TikTok Ltd', engine:'Personalizado', version:'36.1.4',
    languages:'Español, Inglés, y 40+ idiomas', online:'Sí',
    size:'200 MB',
    thumb:'tiktok.png',
    headerImg:'', screenshots:[],
    description:'TikTok es la plataforma de vídeos cortos que ha revolucionado el entretenimiento. Descubre vídeos creativos, síguete a creadores increíbles y comparte tus propios momentos con el mundo.',
    reqMin:{ OS:'Android 5.0+ / iOS 16.0+', RAM:'2 GB', Storage:'200 MB', Red:'Wi-Fi o 4G' },
    reqRec:{ OS:'Android 10+ / iOS 17+', RAM:'4 GB', Storage:'1 GB', Red:'Wi-Fi' },
    stats:{ downloads:'5B+', rating:'8.2', reviews:'100M', players:'1.7B activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
  {
    id:'youtube-mobile', name:'YouTube', build:'19.45.36', platform:'Android/iOS', platformIcon:'📲',
    categories:['Vídeo','Entretenimiento','Educación','Streaming'],
    date:'2012-02-19', isHot:false, isFree:true, isNew:false,
    developer:'Google LLC', publisher:'Google', engine:'Personalizado', version:'19.45',
    languages:'Español, Inglés, y 80+ idiomas', online:'Sí',
    size:'100 MB',
    thumb:'https://play-lh.googleusercontent.com/lMoItBgdPPVDJsNOVtP26EKHePkwBg-PkuY9NOrc-fumRtTFP4XhpUNk_22syN4Datc',
    headerImg:'', screenshots:[],
    description:'YouTube es la plataforma de vídeo más grande del mundo. Explora millones de videos, canales, música, noticias y más. Suscríbete a tus creadores favoritos y descarga para verlos sin conexión con Premium.',
    reqMin:{ OS:'Android 8.0+ / iOS 16.0+', RAM:'2 GB', Storage:'100 MB', Red:'Wi-Fi o 4G' },
    reqRec:{ OS:'Android 10+ / iOS 17+', RAM:'3 GB', Storage:'500 MB', Red:'Wi-Fi' },
    stats:{ downloads:'5B+', rating:'8.5', reviews:'250M', players:'2.7B activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
  {
    id:'capcut', name:'CapCut — Editor de vídeo', build:'12.3.0', platform:'Android/iOS', platformIcon:'📲',
    categories:['Edición','Creación','Herramientas','Video'],
    date:'2020-04-10', isNew:false, isFree:true, isHot:false,
    developer:'Bytedance', publisher:'Bytedance', engine:'Personalizado', version:'12.3',
    languages:'Español, Inglés, y 30+ idiomas', online:'Parcial',
    size:'200 MB',
    thumb:'capcut.png',
    headerImg:'', screenshots:[],
    description:'CapCut es el editor de vídeo todo-en-uno para móvil. Edita vídeos con efectos, filtros, transiciones y texto animado. Perfecta para crear contenido para TikTok, Instagram y YouTube.',
    reqMin:{ OS:'Android 5.0+ / iOS 13.0+', RAM:'2 GB', Storage:'200 MB', Red:'Recomendado' },
    reqRec:{ OS:'Android 9+ / iOS 16+', RAM:'4 GB', Storage:'1 GB', Red:'Wi-Fi' },
    stats:{ downloads:'1B+', rating:'8.7', reviews:'12M', players:'200M activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
];

const DESKTOP_APPS = [
  {
    id:'steam', name:'Steam', build:'1714488832', platform:'Windows/Mac/Linux', platformIcon:'💻',
    categories:['Tienda','Launcher','Gaming','Comunidad'],
    date:'2003-09-12', isHot:true, isFree:true, isNew:false,
    developer:'Valve Corporation', publisher:'Valve', engine:'Personalizado', version:'2024',
    languages:'Español, Inglés, y 25+ idiomas', online:'Sí - Obligatorio',
    size:'300 MB',
    thumb:'OIP.png',
    headerImg:'',
    screenshots:[],
    description:'Steam es la plataforma de distribución de videojuegos más grande del mundo para PC. Compra, descarga y juega más de 100,000 juegos. Con comunidades, talleres, transmisión y más.',
    reqMin:{ OS:'Windows 10 64-bit / macOS 10.15+ / Ubuntu 12.04+', CPU:'1 GHz', RAM:'1 GB', Storage:'10 GB', Red:'Sí' },
    reqRec:{ OS:'Windows 10/11 64-bit / macOS 13+ / Ubuntu 22.04', CPU:'Dual Core 2 GHz', RAM:'2 GB', Storage:'250 GB SSD', Red:'Wi-Fi 10 Mbps+' },
    stats:{ downloads:'1B+', rating:'9.2', reviews:'N/A', players:'132M activos', peakPlayers:'37,000,000', avgHours:'N/A' }
  },
  {
    id:'discord', name:'Discord', build:'0.0.309', platform:'Windows/Mac/Linux', platformIcon:'💻',
    categories:['Comunicación','Voz','Comunidad','Gaming'],
    date:'2015-05-13', isHot:true, isFree:true, isNew:false,
    developer:'Discord Inc.', publisher:'Discord', engine:'Electron', version:'Stable 309',
    languages:'Español, Inglés, Francés, Alemán, Portugués, Ruso, Chino, Japonés, Coreano, y 15+ idiomas', online:'Sí',
    size:'80 MB',
    thumb:'oip4.ng',
    headerImg:'',
    screenshots:[],
    description:'Discord es la plataforma de comunicación para gamers más popular. Crea y únete a servidores, chatea por voz, vídeo y texto con tus amigos y comunidades. Con más de 19,000 servidores públicos.',
    reqMin:{ OS:'Windows 7+', CPU:'1 GHz', RAM:'256 MB', Storage:'80 MB', Red:'Wi-Fi o Ethernet' },
    reqRec:{ OS:'Windows 10/11 64-bit', CPU:'Dual Core 2 GHz', RAM:'1 GB', Storage:'200 MB', Red:'Wi-Fi 5 Mbps+' },
    stats:{ downloads:'500M+', rating:'9.0', reviews:'N/A', players:'154M activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
  {
    id:'obs-studio', name:'OBS Studio', build:'31.0.0', platform:'Windows/Mac/Linux', platformIcon:'💻',
    categories:['Streaming','Grabación','Broadcasting','Herramientas'],
    date:'2012-09-03', isHot:false, isFree:true, isNew:false,
    developer:'OBS Project', publisher:'OBS Project', engine:'Qt', version:'31.0.0',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Japonés, Coreano, Portugués, Ruso, Chino, y 20+ idiomas', online:'No',
    size:'200 MB',
    thumb:'oip2.png',
    headerImg:'',
    screenshots:[],
    description:'OBS Studio es el software de transmisión en vivo y grabación de pantalla más usado por streamers. Totalmente gratuito y de código abierto, con soporte para Twitch, YouTube, TikTok Live y más.',
    reqMin:{ OS:'Windows 10 64-bit / macOS 13+ / Ubuntu 22.04', CPU:'Intel i5 2.5GHz / AMD Ryzen 5', RAM:'4 GB', GPU:'DX11 / OpenGL 3.3', Storage:'200 MB' },
    reqRec:{ OS:'Windows 11 64-bit / macOS 14+', CPU:'Intel i7 3.5GHz / AMD Ryzen 7', RAM:'8 GB', GPU:'NVIDIA GTX 1060 / AMD RX 580', Storage:'1 GB SSD' },
    stats:{ downloads:'200M+', rating:'9.5', reviews:'N/A', players:'100M activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
  {
    id:'vlc-media', name:'VLC Media Player', build:'3.0.21', platform:'Windows/Mac/Linux', platformIcon:'💻',
    categories:['Multimedia','Reproductor','Video','Herramientas'],
    date:'2001-02-01', isHot:false, isFree:true, isNew:false,
    developer:'VideoLAN', publisher:'VideoLAN', engine:'Qt', version:'3.0.21',
    languages:'Español, Inglés, y 70+ idiomas', online:'No',
    size:'40 MB',
    thumb:'oip3.png',
    headerImg:'',
    screenshots:[],
    description:'VLC es el reproductor multimedia más popular y versátil del mundo. Reproduce prácticamente cualquier formato de vídeo y audio sin necesidad de codecs adicionales. Gratuito y de código abierto.',
    reqMin:{ OS:'Windows 7+ / macOS 10.11+ / Ubuntu 18.04+', CPU:'1 GHz', RAM:'512 MB', Storage:'200 MB', GPU:'Cualquier GPU' },
    reqRec:{ OS:'Windows 10/11 / macOS 13+', CPU:'Dual Core 2 GHz', RAM:'1 GB', Storage:'500 MB', GPU:'Con aceleración hardware' },
    stats:{ downloads:'3B+', rating:'9.4', reviews:'N/A', players:'300M activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
  {
    id:'vs-code', name:'Visual Studio Code', build:'1.95.0', platform:'Windows/Mac/Linux', platformIcon:'💻',
    categories:['Programación','Desarrollo','IDE','Herramientas'],
    date:'2015-04-29', isHot:false, isFree:true, isNew:false,
    developer:'Microsoft', publisher:'Microsoft', engine:'Electron', version:'1.95',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Japonés, Coreano, Portugués, Ruso, Chino, y 15+ idiomas', online:'No',
    size:'80 MB',
    thumb:'oip5.ng',
    headerImg:'',
    screenshots:[],
    description:'Visual Studio Code es el editor de código más popular del mundo de Microsoft. Con soporte para cientos de lenguajes, extensiones, Git integrado, depurador y terminal. Ligero pero extremadamente potente.',
    reqMin:{ OS:'Windows 10 1607+ / macOS 10.15+ / Linux', CPU:'1.6 GHz', RAM:'1 GB', Storage:'500 MB', GPU:'OpenGL 2.0+' },
    reqRec:{ OS:'Windows 11 / macOS 13+', CPU:'Dual Core 2 GHz', RAM:'4 GB', Storage:'1 GB SSD', GPU:'Aceleración hardware' },
    stats:{ downloads:'2B+', rating:'9.6', reviews:'N/A', players:'14M activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
  {
    id:'epic-games', name:'Epic Games Launcher', build:'17.0.0', platform:'Windows/Mac', platformIcon:'💻',
    categories:['Tienda','Launcher','Gaming','Juegos Gratis'],
    date:'2018-09-18', isHot:true, isFree:true, isNew:false,
    developer:'Epic Games', publisher:'Epic Games', engine:'Unreal Engine', version:'17.0',
    languages:'Español, Inglés, Francés, Alemán, Italiano, Japonés, Coreano, Portugués, Ruso, Chino, Turco', online:'Sí',
    size:'500 MB',
    thumb:'https://cdn2.unrealengine.com/Unreal+Engine%2Feg-logo-filled-1255x1272-0eb9d144a0f981d1cbaaa1eb957de7a3207b31bb.png',
    headerImg:'',
    screenshots:[],
    description:'Epic Games Launcher es la tienda de Epic Games con juegos gratis cada semana. Descarga Fortnite, accede a la Epic Games Store y los mejores títulos para PC con ofertas exclusivas permanentes.',
    reqMin:{ OS:'Windows 10 64-bit / macOS 10.14.6+', CPU:'Core i5-7600K / Ryzen 5 1600', RAM:'8 GB', GPU:'NVIDIA GTX 960 / AMD RX 470', Storage:'15 GB' },
    reqRec:{ OS:'Windows 11 64-bit / macOS 13+', CPU:'Core i7-8700K / Ryzen 7 3700X', RAM:'16 GB', GPU:'NVIDIA RTX 2070 / AMD RX 5700 XT', Storage:'15 GB SSD' },
    stats:{ downloads:'500M+', rating:'8.5', reviews:'N/A', players:'245M activos', peakPlayers:'N/A', avgHours:'N/A' }
  },
];